import React from 'react';
import {AlertCircle,CheckCircle,Clock,CreditCard,MoreVertical,XCircle} from 'lucide-react';
import type {Subscription} from '../../types';
interface Props{subscriptions:Subscription[];isLoading:boolean;formatCurrency:(n:number)=>string}
const status=(s:string)=>{switch(s.toLowerCase()){case'active':return <span className="subscriptions-badge subscriptions-badge--active"><CheckCircle size={11}/>Active</span>;case'cancelled':return <span className="subscriptions-badge subscriptions-badge--cancelled"><XCircle size={11}/>Cancelled</span>;case'past_due':return <span className="subscriptions-badge subscriptions-badge--past-due"><AlertCircle size={11}/>Past Due</span>;case'trialing':return <span className="subscriptions-badge subscriptions-badge--trialing"><Clock size={11}/>Trialing</span>;default:return <span className="subscriptions-badge">{s}</span>}}
const plan=(p:string)=><span className={`subscriptions-plan subscriptions-plan--${p.toLowerCase()}`}>{p}</span>;
const billing=(b:string)=><span className={`subscriptions-billing subscriptions-billing--${b.toLowerCase()}`}>{b}</span>;
const SubscriptionsTable:React.FC<Props>=({subscriptions,isLoading,formatCurrency})=>{if(isLoading)return <section className="subscriptions-table-card"><div className="subscriptions-empty-state"><div className="subscriptions-spinner"/><span>Loading subscriptions...</span></div></section>;if(!subscriptions.length)return <section className="subscriptions-table-card"><div className="subscriptions-empty-state"><CreditCard size={48}/><h3>No subscriptions found</h3><p>Try adjusting your filters or add a new subscription.</p></div></section>;return <section className="subscriptions-table-card"><div className="subscriptions-table-scroll"><table className="subscriptions-table"><thead><tr>{['Subscription ID','Seller','Plan','Status','Billing','Amount','Payment Method','Next Billing','Created'].map(h=><th key={h}>{h}</th>)}<th className="subscriptions-table__actions" aria-label="Actions"/></tr></thead><tbody>{subscriptions.map(sub=><tr key={sub.id}>
 <td><span className="subscriptions-table__id">{sub.id}</span></td><td><div className="subscriptions-table__seller">{sub.seller?.businessName||`Seller #${sub.sellerId}`}</div><div className="subscriptions-table__secondary">Seller ID: {sub.sellerId}</div></td><td>{plan(sub.plan)}</td><td>{status(sub.status)}</td><td>{billing(sub.billingCycle)}</td><td><span className="subscriptions-table__amount">{formatCurrency(sub.amount)}</span></td><td><span className="subscriptions-table__payment">{sub.paymentMethod||'—'}</span></td><td className="subscriptions-table__date">{new Date(sub.currentPeriodEnd).toLocaleDateString('en-GB')}</td><td className="subscriptions-table__date">{new Date(sub.createdAt).toLocaleDateString('en-GB')}</td><td className="subscriptions-table__actions"><button type="button" className="subscriptions-icon-button" aria-label={`Actions for ${sub.id}`}><MoreVertical size={18}/></button></td>
 </tr>)}</tbody></table></div></section>};
export default SubscriptionsTable;
